export const PracticeAppsScreen = {
  CHANGING_BACKGROUND: 'CHANGING_BACKGROUND',
  ROLLING_DICE: 'ROLLING_DICE',
  MUSIC_PLAYER: 'MUSIC_PLAYER',
  RUN_ROUTE_FINDER: 'RUN_ROUTE_FINDER',
  BLUE_THEME_HOMEPAGE: 'BLUE_THEME_HOMEPAGE',
  BLUE_THEME_LOGIN: 'BLUE_THEME_LOGIN',
  BLUE_THEME_REGISTER: 'BLUE_THEME_REGISTER',
  PINK_THEME_HOMEPAGE: 'PINK_THEME_HOMEPAGE',
  PINK_THEME_LOGIN: 'PINK_THEME_LOGIN',
  PINK_THEME_REGISTER: 'PINK_THEME_REGISTER',
} as const;

export type PracticeAppsScreenKeys = keyof typeof PracticeAppsScreen;
export type PracticeAppsScreenValues =
  (typeof PracticeAppsScreen)[PracticeAppsScreenKeys];
